description: Simple snake game similar to the one on older mobile phones.
assembly:
  - name: HARDWARIO Core Module
  - name: HARDWARIO LCD Module
  - name: HARDWARIO Battery Module
    optional: true
